# Generated by Django 5.1.7 on 2025-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("RAZORPAY", "RAZORPAY"),
                    ("COD", "COD"),
                    ("ShopEase_WALLET", "ShopEase_WALLET"),
                ],
                max_length=25,
            ),
        ),
    ]
